apiVersion: v1
kind: ConfigMap
metadata:
  name: sofia-config
  namespace: sofia-dental
data:
  # LiveKit Configuration
  LIVEKIT_URL: "ws://livekit-service.sofia-dental.svc.cluster.local:7880"
  LIVEKIT_WS_URL: "wss://voice.sofia-dental.com/livekit"
  LIVEKIT_API_HOST: "livekit-service.sofia-dental.svc.cluster.local:7880"
  
  # Sofia Agent Configuration
  SOFIA_LOG_LEVEL: "DEBUG"
  SOFIA_ENVIRONMENT: "production"
  SOFIA_MAX_CONNECTIONS: "50"
  SOFIA_AUTO_RECONNECT: "true"
  SOFIA_HEARTBEAT_INTERVAL: "30"
  
  # Calendar Configuration
  CALENDAR_URL: "http://dental-calendar-service.sofia-dental.svc.cluster.local:3005"
  CALENDAR_DATABASE_HOST: "postgres-service.sofia-dental.svc.cluster.local"
  CALENDAR_DATABASE_PORT: "5432"
  CALENDAR_DATABASE_NAME: "dental_calendar"
  
  # Performance Tuning
  NODE_ENV: "production"
  PYTHON_ENV: "production"
  MAX_WORKERS: "4"
  WORKER_TIMEOUT: "120"
  
  # Monitoring
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"
  ENABLE_METRICS: "true"
  METRICS_PATH: "/metrics"
  
  # WebRTC Configuration
  WEBRTC_ICE_SERVERS: '[{"urls": ["stun:stun.l.google.com:19302", "stun:stun1.l.google.com:19302"]}]'
  WEBRTC_MEDIA_ENGINE: "opus"
  WEBRTC_AUDIO_CODEC: "opus"
  WEBRTC_VIDEO_CODEC: "h264"
  
  # Security
  ENABLE_CORS: "true"
  ALLOWED_ORIGINS: "https://sofia-dental.com,https://www.sofia-dental.com"
  SESSION_TIMEOUT: "3600"
  TOKEN_EXPIRY: "14400"
---
apiVersion: v1
kind: Secret
metadata:
  name: sofia-secrets
  namespace: sofia-dental
type: Opaque
data:
  # LiveKit API Credentials (base64 encoded)
  LIVEKIT_API_KEY: ZGV2a2V5  # devkey
  LIVEKIT_API_SECRET: c2VjcmV0  # secret
  
  # Database Credentials
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  
  # JWT Secret
  JWT_SECRET: c29maWEtand0LXNlY3JldC1rZXktMjAyNQ==  # sofia-jwt-secret-key-2025
  
  # External API Keys
  GEMINI_API_KEY: ""  # Add your actual Gemini API key here
  
  # SSL/TLS Certificates (if needed)
  TLS_CERT: ""
  TLS_KEY: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sofia-dental
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream livekit {
            server livekit-service.sofia-dental.svc.cluster.local:7880;
        }
        
        upstream calendar {
            server dental-calendar-service.sofia-dental.svc.cluster.local:3005;
        }
        
        upstream sofia-agent {
            server sofia-agent-service.sofia-dental.svc.cluster.local:8080;
        }
        
        # Enable gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        
        # WebSocket support
        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }
        
        server {
            listen 80;
            server_name sofia-dental.com www.sofia-dental.com;
            
            # Health check endpoint
            location /health {
                return 200 'OK';
                add_header Content-Type text/plain;
            }
            
            # Calendar interface
            location / {
                proxy_pass http://calendar;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # CORS headers
                add_header Access-Control-Allow-Origin "https://sofia-dental.com" always;
                add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
                add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;
            }
            
            # LiveKit WebSocket endpoint
            location /livekit/ {
                proxy_pass http://livekit/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # WebSocket specific timeouts
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 300s;
                
                # Buffer settings for real-time communication
                proxy_buffering off;
                proxy_cache off;
            }
            
            # Sofia agent API
            location /sofia/ {
                proxy_pass http://sofia-agent/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # Static files with caching
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                proxy_pass http://calendar;
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: sofia-dental
data:
  livekit.yaml: |
    port: 7880
    bind_addresses:
      - ""
    rtc:
      tcp_port: 7881
      port_range_start: 50000
      port_range_end: 60000
      use_external_ip: true
      
    # WebRTC configuration optimized for browsers
    webrtc:
      ice_servers:
        - urls:
          - stun:stun.l.google.com:19302
          - stun:stun1.l.google.com:19302
      
    # Performance tuning
    room:
      auto_create: true
      max_participants: 100
      empty_timeout: 300
      
    # Enable agent support
    agent:
      enabled: true
      
    # Development keys (replace in production)
    keys:
      devkey: secret
      
    # Logging
    logging:
      level: info
      
    # Redis for scaling (optional)
    redis:
      address: redis-service.sofia-dental.svc.cluster.local:6379