apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit
  namespace: sofia-dental
  labels:
    app: livekit
    component: realtime-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: livekit
  template:
    metadata:
      labels:
        app: livekit
        component: realtime-server
    spec:
      containers:
      - name: livekit
        image: livekit/livekit-server:latest
        ports:
        - containerPort: 7880
          name: http-api
          protocol: TCP
        - containerPort: 7881
          name: rtc-tcp
          protocol: TCP
        - containerPort: 50000
          name: rtc-udp-start
          protocol: UDP
        env:
        - name: LIVEKIT_CONFIG_BODY
          valueFrom:
            configMapKeyRef:
              name: livekit-config
              key: livekit.yaml
        - name: LIVEKIT_KEYS
          valueFrom:
            secretKeyRef:
              name: sofia-secrets
              key: LIVEKIT_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /
            port: 7880
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 7880
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: livekit-config
          mountPath: /etc/livekit
          readOnly: true
      volumes:
      - name: livekit-config
        configMap:
          name: livekit-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - livekit
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: livekit-service
  namespace: sofia-dental
  labels:
    app: livekit
    component: realtime-server
spec:
  selector:
    app: livekit
  ports:
  - name: http-api
    port: 7880
    targetPort: 7880
    protocol: TCP
  - name: rtc-tcp
    port: 7881
    targetPort: 7881
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: livekit-udp-service
  namespace: sofia-dental
  labels:
    app: livekit
    component: realtime-server
    service-type: udp
spec:
  selector:
    app: livekit
  ports:
  - name: rtc-udp
    port: 7882
    targetPort: 50000
    protocol: UDP
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: livekit-hpa
  namespace: sofia-dental
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: livekit
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60