# Sofia Button Trigger RBAC Configuration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sofia-deployment-manager
  namespace: dental-voice

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dental-voice
  name: sofia-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sofia-deployment-manager
  namespace: dental-voice
subjects:
- kind: ServiceAccount
  name: sofia-deployment-manager
  namespace: dental-voice
roleRef:
  kind: Role
  name: sofia-deployment-manager
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for cross-namespace operations if needed
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sofia-global-manager
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
  resourceNames: ["sofia-agent-auto"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sofia-global-manager
subjects:
- kind: ServiceAccount
  name: sofia-deployment-manager
  namespace: dental-voice
roleRef:
  kind: ClusterRole
  name: sofia-global-manager
  apiGroup: rbac.authorization.k8s.io