services:
  # Sofia AI WebSocket Bridge Backend Service
  - type: web
    name: sofia-websocket-backend
    runtime: docker
    region: oregon  # Choose region close to your users (oregon, frankfurt, singapore)
    plan: starter   # Can upgrade to paid plans later
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: false  # Manual deployment control
    envVars:
      # LiveKit Configuration - Your LiveKit Cloud instance
      - key: LIVEKIT_URL
        value: wss://sofia-y7ojalkh.livekit.cloud
      - key: LIVEKIT_API_KEY
        value: APILexYWwak6y55
      - key: LIVEKIT_API_SECRET
        value: ewMkNz2dcz2zRRA6eveAnn8dp8D0kFf7gg1yle06rXxH
      
      # Google AI Configuration - Your Google Generative AI key  
      - key: GOOGLE_API_KEY
        value: AIzaSyDX3AhMx3aMYtw0J_iYcRr4qyfca0uZ1k8
      
      # Database Configuration - SQLite stored on persistent disk
      - key: DATABASE_URL
        value: sqlite:///app/data/appointments.db
      
      # Server Configuration - Render will set PORT automatically, but we specify default
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      
      # Environment Settings
      - key: PYTHON_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: false
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: "1"
        
      # Language and Practice Settings for Sofia
      - key: LANGUAGE
        value: en-US
      - key: PRACTICE_NAME
        value: Sofia Dental Practice
    
    # Persistent disk for SQLite database and logs
    disk:
      name: sofia-data
      mountPath: /app/data
      sizeGB: 2  # 2GB for appointments database and logs