services:
  # Sofia AI Unified Production Server
  - type: web
    name: sofia-ai-production
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/ezekaj/sofia-en.git
    branch: main
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node production-server.js
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LIVEKIT_URL
        value: wss://sofia-y7ojalkh.livekit.cloud
      - key: LIVEKIT_API_KEY
        value: APILexYWwak6y55
      - key: LIVEKIT_API_SECRET
        value: ewMkNz2dcz2zRRA6eveAnn8dp8D0kFf7gg1yle06rXxH
      - key: GOOGLE_API_KEY
        value: AIzaSyCGXSa68qIQNtp8WEH_zYFF3UjIHS4EW2M
      - key: PYTHONPATH
        value: /app
      - key: PYTHON_UNBUFFERED
        value: "1"
    
    # Persistent disk for SQLite database
    disk:
      name: sofia-data
      mountPath: /app/data
      sizeGB: 1

# Custom domains configuration  
domains:
  - name: elosofia.site
    type: apex
  - name: www.elosofia.site
    type: www