services:
  - type: web
    name: sofia-ai-dental-assistant
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: LIVEKIT_URL
        value: wss://sofia-y7ojalkh.livekit.cloud
      - key: LIVEKIT_API_KEY
        value: APILexYWwak6y55
      - key: LIVEKIT_API_SECRET
        value: ewMkNz2dcz2zRRA6eveAnn8dp8D0kFf7gg1yle06rXxH
      - key: GOOGLE_API_KEY
        value: AIzaSyCGXSa68qIQNtp8WEH_zYFF3UjIHS4EW2M
      - key: PORT
        value: 10000
    healthCheckPath: /health
    disk:
      name: sofia-data
      mountPath: /app/data
      sizeGB: 1
    plan: starter